# Uses the attributes HACS component to create a sensor.<camera name>_last_motion for each Camera based on that attribute.
# Can't remember what I use it for at the moment !
sensor:  
  - platform: attributes
    friendly_name: "Last Motion"
    attribute: last_motion
    entities:
      - camera.hall
      - camera.lounge
      - camera.kitchen
      - camera.kitchen_2
      - camera.landing
      - camera.bar
      - camera.drive
      - camera.patio
      - camera.bins
      - camera.gazebo  
