automation:
  - id: turn_off_kate_asleep_with_lights
    alias: Turn off Kate Asleep switch from lights on
    mode: parallel
    trigger:
      - platform: state
        entity_id: light.kates_bedroom_lights     
        to: 'on'    
    condition:
      - condition: state
        entity_id: input_boolean.kate_is_asleep
        state: 'on'          
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.kate_is_asleep  
