automation:
  - id: flic_bedside_kate
    alias: 'Kate Bedside Lights from Flic'

    description: >-
      control lights and others from Bedside Flic

    trigger:
      - platform: event
        event_type: flic
        event_data:
          button_name: bedside_kate

    action:
      - choose:
          - conditions: "{{ trigger.event.data.click_type == 'single' }}"
            sequence:
              - service: light.toggle
                target:
                  entity_id: light.kates_bedroom_lamp

          - conditions: "{{ trigger.event.data.click_type == 'double' }}"
            sequence:
              - service: "input_boolean.turn_{{ states('light.kates_bedroom') }}"
                target:
                  entity_id: input_boolean.kate_is_asleep
              - service: "light.turn_{{ 'off' if is_state('light.kates_bedroom','on') else 'on' }}"
                target:
                  entity_id: light.kates_bedroom

          - conditions: "{{ trigger.event.data.click_type == 'hold' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.kates_bedroom           