automation:
  - id: kate_lightstrip_control_from_brightness
    alias: 'Kate Lightstrip On or Off with hue brightness'
    mode: restart
    
    description: >
      Kate lightstrip on or off with Hue Brightness
      
    trigger:
      - platform: state
        entity_id: light.kates_bedroom
        to: 'off'
      - platform: state
        entity_id: light.kates_bedroom_light
        attribute: brightness
        to: 244
        
    action:
      - choose:
          - conditions: "{{ state_attr('light.kates_bedroom_light','brightness',244) }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.kate_lightstrip          
          - conditions: "{{ is_state('light.kates_bedroom','off') }}"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.kate_lightstrip