#sensor:
#  - platform: mqtt
#    name: "Export Power"
#    device_class: power
#    unit_of_measurement: "kW"
#    icon: mdi:flash-circle
#    state_topic: !secret smart_hild_state_topic
#    value_template: "{% if value_json['elecMtr']['0702']['04']['00']|int(base=16)  > 0 %}0.0{% else %}{{  (value_json.elecMtr['0702']['04']['00'] | int(base=16) / -1000) | round(1)   }}{% endif %}"

sensor:
  - platform: mqtt
    name: "MQTT Export Power"
    device_class: power
    unit_of_measurement: "kW"
    icon: mdi:flash
    state_topic: !secret smart_hild_state_topic
    value_template: "{{  (value_json.elecMtr['0702']['04']['01'] | int(base=16) / 1000) | round(1)   }}"


  - platform: template
    sensors:
      export_power_integration:
        friendly_name: Export Power
        unit_of_measurement: "kW"
        value_template: "{% if (states('sensor.electricity_consumption') | float ) < 20.0 %}{{ ((states('sensor.electricity_consumption') | float) / -1000.0) | round(2) }}{% else %}0.0{% endif %}"


#sensor:
#  - platform: mqtt
#    name: "Export Power"
#    device_class: power
#    unit_of_measurement: "kW"
#    icon: mdi:flash
#    state_topic: !secret smart_hild_state_topic
#    value_template: "{% if value_json['elecMtr']['0702']['04']['00']|int(base=16)  > 0 %}0.0{% else %}{{  (value_json.elecMtr['0702']['04']['00'] | int(base=16) / -1000) | round(1)   }}{% endif %}"


#  - platform: template
#    sensors:
#      export_power:
#        friendly_name: Export Power
#        unit_of_measurement: "kW"
#        value_template: "{% if (states('sensor.electricity_consumption') | float ) <- 20.0 %}{{ ((states('sensor.electricity_consumption') | float) / -1000.0) | round(2) }}{% else %}0.0{% endif %}"
#value_template: "{% if value_json['elecMtr']['0702']['04']['00']|int(base=16)  > 100000 or value_json['elecMtr']['0702']['04']['00']|int(base=16)  < 0 %}0.0{% else %}{{  (value_json.elecMtr['0702']['04']['00'] | int(base=16) / 1000) | round(1)   }}{% endif %}"        
