sensor:
  - platform: template
    sensors:
      electricity_demand_rounded:
        friendly_name: "Load"
        unit_of_measurement: 'kW'
        value_template:  "{{ ((states('sensor.import_power') | float )/ 1000.0) | round(1) }}"