automation:
  - id: dimmer_control_utility_lights
    alias: 'Dimmer Control of Utility Lights'
    mode: restart
    trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: "00:17:88:01:04:f2:d5:fb"
    - platform: state
      entity_id: light.utility_light
      to: 'off'      
    action:
      - choose:
          - conditions: "{{ trigger.entity_id == 'light.utility_light' }}"
            sequence:
              - service: input_boolean.turn_off
                entity_id: input_boolean.utility_light_manually_on            
        default:
          - service: input_boolean.turn_{{ trigger.event.data.args.button }}
            entity_id: input_boolean.utility_light_manually_on
          - service: light.turn_{{ trigger.event.data.args.button }}
            entity_id: light.utility_light

