automation:
  - id: washing_machine_progress_test
    alias: "Washing Machine Progress Test"
    mode: single    
    trigger:
#      - platform: state
#        entity_id: input_number.washing_machine_power_test    
      - platform: numeric_state
        entity_id: input_number.washing_machine_power_test
        above: 0.0
      - platform: numeric_state
        entity_id: input_number.washing_machine_power_test
        above: 5.0        
      - platform: numeric_state
        entity_id: input_number.washing_machine_power_test
        above: 18.0                
      - platform: numeric_state
        entity_id: input_number.washing_machine_power_test
        above: 100.0               
      - platform: numeric_state
        entity_id: input_number.washing_machine_power_test
        above: 700.0                        
      - platform: numeric_state
        entity_id: input_number.washing_machine_power_test
        below: 700.0
      - platform: numeric_state
        entity_id: input_number.washing_machine_power_test
        above: 1500.0       
      - platform: numeric_state
        entity_id: input_number.washing_machine_power_test
        below: 10.0            
      - platform: numeric_state
        entity_id: input_number.washing_machine_power_test
        below: 1.0                    
      - platform: numeric_state
        entity_id: input_number.washing_machine_power_test
        below: 0.01
    action:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: input_number.washing_machine_power_test
                above: 700.0
            sequence:
              - service: input_text.set_value
                data:
                  entity_id: input_text.washing_machine_progress_test
                  value: 'Heating'       
    #          - delay: '00:01:00'
          - conditions:
              - condition: numeric_state
                entity_id: input_number.washing_machine_power_test
                above: 200.0
                below: 700
            sequence:
              - service: input_text.set_value
                data:
                  entity_id: input_text.washing_machine_progress_test
                  value: 'final spin'  
      #        - delay: '00:01:00'  
          - conditions:
              - condition: numeric_state
                entity_id: input_number.washing_machine_power_test
                above: 100.0
                below: 200.0
            sequence:
              - service: input_text.set_value
                data:
                  entity_id: input_text.washing_machine_progress_test
                  value: 'spin'     
     #         - delay: '00:01:00'
          - conditions:
              - condition: numeric_state
                entity_id: input_number.washing_machine_power_test
                above: 6.0
              - condition: state
                entity_id: input_text.washing_machine_progress_test
                state: 'Waiting to Start'
  #            - delay: '00:01:00'
            sequence:
              - service: input_text.set_value
                data:
                  entity_id: input_text.washing_machine_progress_test
                  value: 'Filling'      
   #           - delay: '00:01:00'  
          - conditions:
              - condition: numeric_state
                entity_id: input_number.washing_machine_power_test
                above: 0.0
                below: 0.2
              - condition: state
                entity_id: input_text.washing_machine_progress_test
                state: 'off'
#              - delay: '00:01:00'
            sequence:
              - service: input_text.set_value
                data:
                  entity_id: input_text.washing_machine_progress_test
                  value: 'Waiting to Start'
 #             - delay: '00:01:00'
          - conditions:
              - condition: numeric_state
                entity_id: input_number.washing_machine_power_test
                below: 0.01
            sequence:
              - service: input_text.set_value
                data:
                  entity_id: input_text.washing_machine_progress_test
                  value: 'off'   
        #      - delay: '00:01:00'
          - conditions:
              - condition: numeric_state
                entity_id: input_number.washing_machine_power_test
                below: 0.1
            sequence:
              - service: input_text.set_value
                data:
                  entity_id: input_text.washing_machine_progress_test
                  value: 'Emptied'   
        #      - delay: '00:01:00'
          - conditions:
              - condition: numeric_state
                entity_id: input_number.washing_machine_power_test
                below: 10.0
            sequence:
              - service: input_text.set_value
                data:
                  entity_id: input_text.washing_machine_progress_test
                  value: 'finishing'      
       #       - delay: '00:01:00'   
        default:
          - service: input_text.set_value
            data:
              entity_id: input_text.washing_machine_progress_test
              value: 'unknown'      
#          - delay: '00:01:00'
    