automation:
  - id: garden_colour_lights_on_when_dark
    alias: 'Garden Colour Lights on when dark'
    mode: restart
    
    description: >-
      Lights on at dusk

    trigger: 
      - platform: state
        entity_id: binary_sensor.dark_outside
        to: 'on'
      - platform: state
        entity_id: alarm_control_panel.texecom
        to: 'disarmed'        
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded    

    action:
      - choose:
          - conditions: "{{ is_state('binary_sensor.dark_outside','on') and is_state('switch.sarah_is_asleep','off') and is_state('switch.bruce_is_asleep','off') and is_state('alarm_control_panel.texecom','disarmed')}}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.garden_colour

        default:
          - service: light.turn_off
            target:
              entity_id: light.garden_colour        