automation:
  - id: garden_lights_on_with_motion
    alias: Garden Lights on with motion or gate
    mode: restart
    trigger: 
      - platform: state
        entity_id: 
          - binary_sensor.back_door        
          - binary_sensor.back_gate_door
          - binary_sensor.conservatory_door   
          - binary_sensor.patio_motion    
          - binary_sensor.patio_garage_motion
        to: 'on'
      - platform: state
        entity_id: 
          - binary_sensor.motion_gazebo
          - binary_sensor.motion_bins
          - binary_sensor.motion_patio
        to: person
        attribute: event_object   
    condition:
      - condition: state
        entity_id: sensor.dark_outside
        state: 'True'
      - condition: state
        entity_id: input_boolean.patio_lights_manually_on
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.patio_lights
      - delay: 00:02:00
      - service: light.turn_off
        entity_id: light.patio_lights        