sensor:
  - platform: template
    sensors:
      outside_light_rounded:
        friendly_name: "Outside Light"
        value_template: "{{ states('sensor.outside_light') | int }}"
        device_class: "illuminance"
        unit_of_measurement: "lx"