sensor:
  - platform: min_max
    name: Outside Temp
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.patio_temperature
      - sensor.patio_garage_temperature
      - sensor.drive_temperature
