automation:
  - id: flic_bedside_sophie
    alias: 'Sophie Bedside Lights from Flic'

    description: >-
      control lights and Asleep switch from Bedside Flic

    trigger:
      platform: event
      event_type: flic
      event_data:
        button_name: bedside_sophie

    action:
      - choose:
          - conditions: "{{ trigger.event.data.click_type == 'single' }}"
            sequence:
              - service: light.toggle
                target:
                  entity_id: light.sophies_bedroom_bedhead

          - conditions: "{{ trigger.event.data.click_type == 'double' }}"
            sequence:
              - service: "input_boolean.turn_{{ states('light.sophies_bedroom') }}"
                target:
                  entity_id: input_boolean.sophie_is_asleep
              - service: "light.turn_{{ 'off' if is_state('light.sophies_bedroom','on') else 'on' }}"
                target:
                  entity_id: light.sophies_bedroom

          - conditions: "{{ trigger.event.data.click_type == 'hold' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.sophies_bedroom          