automation:
  - id: flic_kitchen_sonos_source
    alias: Kitchen sonos Radio from Flic
    description: switch on Sonos and set to Radio
    trigger:
      platform: event
      event_type: flic
      event_data:
        button_name: kitchen_radio
    action:
      - choose:
          - conditions: "{{ trigger.event.data.click_type == 'single' and is_state('media_player.kitchen_sonos','playing') and state_attr('media_player.kitchen_sonos','source') == 'BBC Radio 1 England'}}"
            sequence:
              - service: sonos.unjoin
                entity_id: media_player.kitchen_sonos          
              - service: media_player.media_pause
                entity_id: media_player.kitchen_sonos
          - conditions: "{{ trigger.event.data.click_type == 'single' }}"
            sequence:
              - service: sonos.unjoin
                entity_id: media_player.kitchen_sonos          
              - service: media_player.select_source
                data:
                  entity_id: media_player.kitchen_sonos
                  source: BBC Radio 1 England                  
          - conditions: "{{ trigger.event.data.click_type == 'double' and is_state('media_player.kitchen_sonos','playing') and state_attr('media_player.kitchen_sonos','source') == 'BBC Radio 2'}}"
            sequence:
              - service: sonos.unjoin
                entity_id: media_player.kitchen_sonos          
              - service: media_player.media_pause
                entity_id: media_player.kitchen_sonos
          - conditions: "{{ trigger.event.data.click_type == 'double' }}"
            sequence:
              - service: sonos.unjoin
                entity_id: media_player.kitchen_sonos          
              - service: media_player.select_source
                data:
                  entity_id: media_player.kitchen_sonos
                  source: BBC Radio 2               
          - conditions: "{{ trigger.event.data.click_type == 'hold' and is_state('media_player.kitchen_sonos','playing') and state_attr('media_player.kitchen_sonos','source') == 'KISS 97.2 (Top 40 & Pop Music)'}}"
            sequence:
              - service: sonos.unjoin
                entity_id: media_player.kitchen_sonos          
              - service: media_player.media_pause
                entity_id: media_player.kitchen_sonos   
          - conditions: "{{ trigger.event.data.click_type == 'hold' }}"
            sequence:
              - service: sonos.unjoin
                entity_id: media_player.kitchen_sonos                 
              - service: media_player.select_source
                data:
                  entity_id: media_player.kitchen_sonos                    
                  source: KISS 97.2 (Top 40 & Pop Music)                       
            