automation:
  - id: cupboard_and_worktop_on_when_lights_2_on_first
    alias: Turn on cupboard when kitchen 2 lights on first
    trigger: 
      - platform: state
        entity_id: light.kitchen_ceiling_2
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: 
          - light.kitchen_ceiling_1
          - light.kitchen_ceiling_3
          - light.kitchen_ceiling_4
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: 
          - light.kitchen_cupboard 
          - light.kitchen_worktop