automation:
  - id: weeklysnapshot
    alias: dailysnapshot
    initial_state: True
    trigger:
      - platform: time
        at: 03:00:00
    action:
    - service: hassio.snapshot_full
      data:
        name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
