---
#
# Purge my recorder database every hour, to keep things nice and tight.
#
automation:
- id: purge_recorder_database
  description: Purge recorder database
  alias: system_recorder_purge
  mode: single
  trigger:
    - platform: time_pattern
      minutes: 12
  action:
    - service: recorder.purge
