---
#
# Sunday morning, early morning, repack the recorder database.
# This keeps the disk usage low and nice by reclaiming space
# taken by the MySQL InnoDB database.
#
automation:
- id: repack_recorder_database
  description: Repack recorder database
  alias: system_recorder_repack
  mode: single
  trigger:
    - platform: time
      at: '05:55:00'
  condition:
    - condition: time
      weekday:
        - sun
  action:
    - service: recorder.purge
      data:
        repack: true
