automation:
- id: system_start_notication
  description: Send notification on Home Assistant start
  alias: system_start_notification
  mode: single
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: telegram_bot.send_message
      data:
        chat_id: !secret telegram_chat_id_bruce
        message: Home Assistant is starting up again 🎉
        message_tag: "startup"

