automation:
  - id: powerwall_powercut_actions
    alias: 'Powerwall: Turn off high loads and announce powercut'
    description: Powercut handling
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.grid_status
        to: 'off'
      - platform: state
        entity_id: binary_sensor.electricity_supply
        to: 'off'
    action:
      - service: logbook.log
        data:
          name: Powercut !
          entity_id: binary_sensor.grid_status
          message: Powercut !
      - service: telegram_bot.send_message
        data:
          target: !secret telegram_chat_id_bruce_and_sarah
          title: There is a powercut!
          message: "HotTub and Car Chargers switched off. Powerwall capacity is {{ states('sensor.powerwall_charge_corrected') }}%"
      - service: switch.turn_off
        entity_id: switch.hottub_power
      - service: script.zappi_mode_paddy
        data:
          mode: 'stop'
      - service: script.zappi_mode_jyggy
        data:
          mode: 'stop'
          
