sensor:
  - platform: template
    sensors:
      grid_to_battery:
        unique_id: grid_to_battery
        friendly_name: "Grid to Battery"
        unit_of_measurement: 'kWh'
        value_template: "{{ ((states('sensor.zappi_jyggy_grid_import') | float) - (states('sensor.harvi_home') | float) - (states('sensor.solaredge_ac_power_kw_output') | float)) if ((states('sensor.harvi_powerwall_charge') | float) > 0.0)  and  ((states('sensor.zappi_jyggy_grid_import') | float) > 0.0) else 0.0 }}"
