automation:
  - id: flichub_click_battery_status
    alias: Flic button battery updates from Flic Hub
    mode: queued
    
    description: >
      Flic Button commands battery update from flic hub

    trigger:
      - platform: event
        event_type: flic
  
    variables: 
      button_name: "{{ trigger.event.data.button_name }}"

    action:       
      - service: input_number.set_value  
        data:
          entity_id: "input_number.{{ button_name }}_battery"
          value: "{{ trigger.event.data.battery_status }}"