automation:
  - id: tv_off_from_iphone
    alias: Action Turn TV Off
    #initial_state: true
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: 'tv_off'
    action:
      - service: script.skytv_turn_off
