automation:
  - id: link_jyggy_charge_limit
    alias: Link Jyggy Charge Limit
    trigger:
      - platform: state
        entity_id: input_number.jyggy_charge_limit
      - platform: state
        entity_id: sensor.jyggy_charge_limit_soc
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded             
    action:
      - choose:
          - conditions: "{{ trigger.entity_id == 'input_number.jyggy_charge_limit'}}"
            sequence:
              - service: rest_command.jyggy_api
                data:
                  teslafi_token: !secret teslafi_token                 
                  jyggy_command: "set_charge_limit&charge_limit_soc={{ states('input_number.jyggy_charge_limit') | int }}"
        default:
          - service: input_number.set_value
            data: 
              entity_id: input_number.jyggy_charge_limit
              value: "{{ states('sensor.jyggy_charge_limit_soc') }}"