automation:
  - id: link_jyggy_charge_limit
    alias: Link Jyggy Charge Limit
    
    description: >
      Link Jyggy Charge Limit to Input Number
      
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded             
      - platform: state
        entity_id: 
          - input_number.jyggy_charge_limit
          - sensor.jyggy_charge_limit_soc
          
    action:
      - choose:
          - conditions: "{{ trigger.entity_id == 'input_number.jyggy_charge_limit'}}"
            sequence:
              - service: rest_command.jyggy_api
                data:
                  teslafi_token: !secret teslafi_token                 
                  jyggy_command: "set_charge_limit&charge_limit_soc={{ states('input_number.jyggy_charge_limit') | int }}"
        default:
          - service: input_number.set_value
            target: 
              entity_id: input_number.jyggy_charge_limit
            data:
              value: "{{ states('sensor.jyggy_charge_limit_soc') }}"