sensor:
  - platform: template
    sensors:
      jyggy_speed:
        value_template: "{{ state_attr('sensor.jyggy_sensor','speed') }}"
        friendly_name: "Speed"
        unit_of_measurement: 'mph'