automation:
  - id: bar_lights_when_door_opened
    alias: Bar Lights on from door
    description: Bar Lights on when door opened
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.bar_door
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: sensor.dark_outside
        state: 'True'
      - condition: state
        entity_id: light.bar_lights
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: 
            - light.bar_bar
            - light.bar_palm
          brightness: 75
