automation:
  - id: flic_bedside_guest
    alias: 'Guest Bedside Lights from Flic'
    mode: queued

    description: >-
      control lights and others from Bedside Flic

    trigger:
      - platform: event
        event_type: flic
        event_data:
          button_name: bedside_guest

    action:
      - choose:
          - conditions: "{{ trigger.event.data.click_type == 'single' }}"
            sequence:
              - service: light.toggle
                target:
                  entity_id: light.guest_bedroom_bedside

          - conditions: "{{ trigger.event.data.click_type == 'double' }}"
            sequence:
              - service: "input_boolean.turn_{{ states('light.guest_bedroom') }}"
                target:
                  entity_id: input_boolean.guest_is_asleep
              - service: "light.turn_{{ 'off' if is_state('light.guest_bedroom','on') else 'on' }}"
                target:
                  entity_id: light.guest_bedroom
                
          - conditions: "{{ trigger.event.data.click_type == 'hold' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.guest_bedroom             
