binary_sensor:
  - platform: template
    sensors:
      elec_voltage_out_of_spec:
        unique_id: elec_voltage_out_of_spec
        friendly_name: "Voltage Too High or Low"
        value_template: "{{ (states('sensor.apc_ups_input_voltage') | float > 253.0) or (states('sensor.apc_ups_input_voltage') | float < 216.2) }}"
          