automation:
  # Turn off lights from ios notifcation button
  - id: turn_off_lights
    alias: Turn off all lights
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: 'all_lights_off'    
      - platform: event
        event_type: ios.notification_action_fired
        event_data:
          actionName: TURN_OFF_LIGHTS
    action:
      service: light.turn_off
      data:
        entity_id: light.home