automation:
  - id: wardrobe_bars_on_when_doors_open
    alias: Turn on or off wardrobe bars with two wardrobe doors
    mode: restart
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
      - platform: state
        entity_id:
          - binary_sensor.master_bedroom_wardrobe_door_1
          - binary_sensor.master_bedroom_wardrobe_door_2
        to: 'on'
    condition:
      - condition: state
        entity_id: switch.sarah_is_asleep
        state: 'off'
      - condition: state
        entity_id: switch.bruce_is_asleep
        state: 'off'
    action:
      - choose:
          - conditions: >
              {{ is_state('light.master_bedroom_wardrobe_bars','off') 
              and (trigger.entity_id == 'binary_sensor.master_bedroom_wardrobe_door_1' 
              or trigger.entity_id == 'binary_sensor.master_bedroom_wardrobe_door_2') }}
            sequence:
              - service: light.turn_on
                entity_id: light.master_bedroom_wardrobe_bars
              - wait_for_trigger:
                  - platform: template
                    value_template: "{{ is_state('binary_sensor.master_bedroom_wardrobe_door_1','off') and is_state('binary_sensor.master_bedroom_wardrobe_door_2','off') }}"
                timeout: 00:10:00
                continue_on_timeout: true      
              - service: light.turn_off
                entity_id: light.master_bedroom_wardrobe_bars
        default:
          - delay: 00:10:00
          - service: light.turn_off
            entity_id: light.master_bedroom_wardrobe_bars
      