automation:
  - id: flic_bedside_bruce
    alias: Bruce Bedside Lights from Flic
    mode: queued
    description: control lights and others from Bedside Flic
    trigger:
      - platform: event
        event_type: flic
        event_data:
          button_name: bedside_bruce
    action:
      - choose:
          - conditions: "{{ trigger.event.data.click_type == 'single' and is_state('alarm_control_panel.full_set','armed_night')}}"
            sequence:
              - service: input_text.set_value
                data:
                  entity_id: input_text.alarm_user
                  value: 'Bruce'               
              - service: light.toggle
                entity_id: light.master_bedroom_bedside_left    
              - service: telegram_bot.send_message
                data:
                  target: !secret telegram_chat_id_bruce
                  message: "Alarm disarming.............."
                  message_tag: alarm_disarming             
              - service: alarm_control_panel.alarm_disarm
                data:
                  entity_id: alarm_control_panel.full_set
                  code: !secret alarm_code
              - wait_for_trigger:
                  - platform: state
                    entity_id: alarm_control_panel.full_set
                    to: disarmed
                timeout: 00:00:20
              - service: telegram_bot.edit_message
                data:
                  message_id: "{{ states('input_text.alarm_disarming_message_id') }}"                
                  chat_id: !secret telegram_chat_id_bruce
                  message: "Alarm currently {{states('alarm_control_panel.full_set').replace('_',' ')}}"
          - conditions: "{{ trigger.event.data.click_type == 'single' and is_state('input_boolean.someone_has_been_downstairs','off') }}"
            sequence:
              - service: light.toggle
                entity_id: light.master_bedroom_bedside_left
              - service: telegram_bot.send_message
                data:
                  target: !secret telegram_chat_id_bruce
                  message: "Alarm currently {{states('alarm_control_panel.full_set').replace('_',' ')}}"                
      
          - conditions: "{{ trigger.event.data.click_type == 'single' }}"
            sequence:
              - service: light.toggle
                entity_id: light.master_bedroom_bedside_left
          - conditions: "{{ trigger.event.data.click_type == 'double' }}"
            sequence:
              - service: light.turn_off
                entity_id: 
                  - light.master_bedroom_wall_left
                  - light.master_bedroom_wall_right
                  - light.master_bedroom_lamp
                  - light.master_bedroom_wardrobe
                  - light.master_bedroom_wardrobe_bars
                  - light.master_bedroom_bedside_left
              - service: switch.turn_off
                entity_id: switch.electric_blanket_bruce     
              - service: input_boolean.turn_on
                entity_id: input_boolean.bruce_is_asleep
              - condition: template
                value_template: "{{ (is_state('input_boolean.sarah_is_asleep','on') or states('person.sarah_hartley')|lower != 'home') and is_state('alarm_control_panel.full_set','disarmed') and is_state('binary_sensor.lounge_door','off') and is_state('binary_sensor.kitchen_door','off') }}"
              - service: light.turn_on
                data:
                  entity_id: light.master_bedroom_bedside_left
                  brightness: 10
                  rgb_color: [255,0,0]
                  transition: 1
              - service: telegram_bot.send_message
                data:
                  target: !secret telegram_chat_id_bruce_and_sarah
                  message: "Alarm arming.............."
                  message_tag: alarm_arming                  
              - service: alarm_control_panel.alarm_arm_night 
                data:
                  entity_id: alarm_control_panel.full_set
                  code: !secret alarm_code
              - wait_for_trigger:
                  - platform: state
                    entity_id: alarm_control_panel.full_set
                    to: armed_night
                timeout: 00:00:20
              - service: light.turn_on
                data:
                  entity_id: light.master_bedroom_bedside_left
                  brightness: 10
                  rgb_color: [0,255,0]
                  transition: 1                
              - service: telegram_bot.edit_message
                data:
                  message_id: "{{ states('input_text.alarm_arming_message_id') }}"                
                  chat_id: !secret telegram_chat_id_bruce_and_sarah
                  message: "Alarm currently {{states('alarm_control_panel.full_set').replace('_',' ')}}"
              - service: light.turn_on
                data:
                  entity_id: light.master_bedroom_bedside_left
                  brightness: 10
                  color_temp: 447
                  transition: 1
              - delay: '00:00:01'
              - service: light.turn_off
                entity_id: 
                  - light.master_bedroom_bedside_left
                  - light.downstairs
                  - light.landing_lights
                  - light.hall_stairs_lightstrip
                  - light.kitchen_floor_lamp
                
          - conditions: "{{ trigger.event.data.click_type == 'hold' }}"
            sequence:
              - service: fan.turn_off
                entity_id: fan.master_bedroom_fan
              - service: switch.turn_off
                entity_id: switch.electric_blanket_sarah                
              - service: light.turn_off
                entity_id:
                  - light.master_bedroom_lights
                  - light.downstairs_lights
                  - light.outside_lights                  
                  - light.landing_lights
                  - light.hall_stairs_lightstrip
                  