sensor:
  - platform: template
    sensors:
      master_bedroom_environment_max_co2:
        friendly_name: "Max CO2"
        value_template: "{{ state_attr('sensor.master_bedroom_co2_statistics','max_value') | int }}"
        icon_template: mdi:molecule-co2
        unit_of_measurement: 'ppm'
