automation:
  - id: paddy_enable_charge_when_below_set_price
    alias: 'Paddy Enable Charge When Below Set Price'
    description: Switch on automation when price changed
    trigger:
      - entity_id: input_number.paddy_charge_below_x_pence
        platform: state
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.charge_paddy_when_below_set_price
