automation:
  - id: eddi_off_at_agile_peak
    alias: 'Hot Water: Turn off for Peak'

    description: >
      Eddi off at Peak
    
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded      
      - platform: state
        entity_id: binary_sensor.agile_peak
  
        
    action:
      - service: script.eddi_on_or_off
        data:
          mode: "{{ 'on' if is_state('binary_sensor.agile_peak','off') else 'off' }}"
      - delay: 2          
      - repeat:
          sequence:
            - service: homeassistant.update_entity
              entity_id: sensor.eddi_cmt
            - delay: 2               
          until: "{{ states('sensor.eddi_cmt') | int > 250 }}"
      - service: homeassistant.update_entity
        target:
          entity_id: sensor.eddi 
