automation:
  - id: eddi_on_when_powerwall_full
    alias: 'Hot Water: Turn on when powerwall full'
    description: When Powerwall full
    trigger:
      - platform: numeric_state
        entity_id: sensor.powerwall_charge
        below: 95       
      - platform: numeric_state
        entity_id: sensor.powerwall_charge
        above: 97                
      - platform: numeric_state
        entity_id: sensor.powerwall_charge
        above: 98   
      - platform: numeric_state
        entity_id: sensor.powerwall_charge
        above: 99
      - platform: time    
        at: 
          - "15:59:50"      
          - "19:00:10"
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded              
    action:
      - choose:
          - alias: "Turn on Eddi if Powerwall full, solar produced and not peak"    
            conditions:  
              - condition: state
                entity_id: sensor.eddi_status
                state: "stopped"
              - condition: numeric_state
                entity_id: sensor.solaredge_ac_power_output
                above: 500    
              - condition: numeric_state
                entity_id: sensor.powerwall_charge
                above: 97                   
              - condition: not
                conditions:
                  - condition: time          
                    after: "15:59:45"
                    before: "19:00:00"     
            sequence:        
              - service: script.eddi_on_or_off
                data:
                  mode: "on"
              - delay: '00:00:02'          
              - alias: repeat this
                repeat:
                  sequence:
                    - service: homeassistant.update_entity
                      entity_id: sensor.eddi_cmt
                    - delay: '00:00:02'               
                  until: "{{ states('sensor.eddi_cmt') | int > 250 }}"
              - service: homeassistant.update_entity
                entity_id: sensor.eddi 
        default:
          - alias: "Turn off Eddi, peak, Powerwall not full or no solar"
            service: script.eddi_on_or_off
            data:
              mode: "off"
          - delay: '00:00:02'          
          - alias: repeat this
            repeat:
              sequence:
                - service: homeassistant.update_entity
                  entity_id: sensor.eddi_cmt
                - delay: '00:00:02'               
              until: "{{ states('sensor.eddi_cmt') | int > 250 }}"
          - service: homeassistant.update_entity
            entity_id: sensor.eddi         

     