automation:
  - id: manage_car_charging
    alias: 'Manage Car Charging'

    description: >
      Manage Car Charging

    trigger:
      - platform: numeric_state
        entity_id: sensor.powerwall_charge_corrected
        above: 95
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded      
      - platform: state
        entity_id: 
          - binary_sensor.agile_peak
          - binary_sensor.agile_plunge            
          - binary_sensor.jyggy_below_max_charge_cost
          - binary_sensor.paddy_below_max_charge_cost
          - binary_sensor.paddy_needs_charge          
          - binary_sensor.jyggy_needs_charge               
      - platform: state
        entity_id: 
          - binary_sensor.jyggy_plugged_in
          - binary_sensor.paddy_plugged_in
        to: 'on'          
     
    action:
      - service: script.zappi_mode
        data:
          serial: !secret zappi_serial_jyggy
          name: "jyggy"
          mode: "{%- if is_state('binary_sensor.jyggy_plugged_in','off') or is_state('binary_sensor.jyggy_needs_charge','off') or is_state('binary_sensor.agile_peak','on') -%}Stopped{%- elif is_state('binary_sensor.agile_plunge','on') or is_state('binary_sensor.jyggy_below_max_charge_cost','on') -%}Fast{%- else -%}Eco+{%- endif -%}"

#      - delay: 30
      
      - service: script.zappi_mode
        data:
          serial: !secret zappi_serial_paddy
          name: "paddy"          
          mode: "{%- if is_state('binary_sensor.paddy_plugged_in','off') or is_state('binary_sensor.paddy_needs_charge','off') or is_state('binary_sensor.agile_peak','on') -%}Stopped{%- elif is_state('binary_sensor.agile_plunge','on') or is_state('binary_sensor.paddy_below_max_charge_cost','on') -%}Fast{%- else -%}Eco+{%- endif -%}"

