automation:
  - id: link_zappi_jyggy_charge_mode
    alias: Link Jyggy Charge Mode Drop Down
    trigger:
      - platform: state
        entity_id: input_select.zappi_jyggy_charge_mode
      - platform: state
        entity_id: sensor.zappi_jyggy_mode
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded      
    condition: "{{ states('sensor.zappi_jyggy_mode') != Unavailable }}"
    action:
      - choose:
          - conditions: "{{ trigger.entity_id == 'input_select.zappi_jyggy_charge_mode'}}"
            sequence:
              - service: script.zappi_mode_jyggy
                data:
                  mode: "{{ states('input_select.zappi_jyggy_charge_mode') }}"
        default:
          - service: input_select.select_option
            data: 
              entity_id: input_select.zappi_jyggy_charge_mode
              option: "{{ states('sensor.zappi_jyggy_mode') }}"
   