sensor:
  - platform: template
    sensors:
      zappi_cars:
        friendly_name_template: 'Zappi - Cars'
        availability_template: "{{ states('sensor.zappi_paddy') and states('sensor.zappi_jyggy') }}"        
        value_template: "{{ (( states('sensor.zappi_jyggy_power') | float + states('sensor.zappi_paddy_power') | float )  ) | round(1) }}"
        unit_of_measurement: 'kW'
        icon_template: mdi:car-electric
        device_class: power   
       
