sensor:
  - platform: template
    sensors:
      zappi_jyggy_power:
        friendly_name: 'Zappi Jyggy - Power'
        availability_template: "{{ states('sensor.zappi_jyggy') }}"     
        value_template: "{% if state_attr('sensor.zappi_jyggy','div') | float > 0.0 %}{{ (state_attr('sensor.zappi_jyggy','div') / 1000 ) | round(2) }}{% else %}0.0{% endif %}"
        unit_of_measurement: kW
        device_class: power        
        icon_template: mdi:ev-station
