sensor:
  - platform: template
    sensors:
      zappi_jyggy_mode:
        friendly_name_template: 'Zappi Jyggy Mode' 
        availability_template: "{{ states('sensor.zappi_jyggy') }}"
        value_template: >
          {% if states('sensor.zappi_jyggy') == Unavailable %}Unavailable{% 
          else %}{% set mapper = {0:'zero',1:'Fast',2:'Eco',3:'Eco+',4:'Stopped'}%}
          {{mapper[state_attr('sensor.zappi_jyggy','zmo')] }}{% endif %}          