binary_sensor:
  - platform: template
    sensors:
      paddy_needs_charge:
        value_template: "{{ states('sensor.vf1ag000366115079_battery_level')|int < states('input_number.paddy_charge_limit')|int }}"
        friendly_name: "Paddy Needs Charge"
        icon_template: mdi:flash