sensor:
- platform: template
  sensors:
    paddy_charging_power:
      friendly_name: "Charging Power"
      unit_of_measurement: "kW"
      value_template: "{% if is_state('binary_sensor.vf1ag000366115079_charging','on') %}{{ states('sensor.vf1ag000366115079_charging_power') }}{% else %}0.0{% endif %}"