automation:
  # Someone has arrived - disarm alarm
  - id: disarm_alarm_when_arriving_home
    alias: Disarm alarm when someone arrives home
    description: disarm alarm if somone home home  
    mode: single
    trigger:
      platform: state
      entity_id: 
        - binary_sensor.front_door
        - binary_sensor.back_door    
        - binary_sensor.conservatory_door
      from: 'off'        
      to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.was_alarm_armed
        state: 'on'
    action:
      - service: input_text.set_value
        data:
          entity_id: input_value.alarm_user
          value: "{{ states('input_text.last_person_to_arrive') }}"
      - service: light.turn_on
        entity_id: light.hall_stairs_lightstrip
        data:
          brightness: 42
          color_temp: 396
      - delay: 00:00:02
      - service: telegram_bot.send_message
        data:
          target: !secret telegram_chat_id_bruce_and_sarah
          title: "{{ states('input_text.last_person_to_arrive') }} is arriving."
          message: "Alarm is armed"
          message_tag: alarm_disarming                  
      
      - wait_template: "{{ is_state('group.someone_home','home') }}"
        timeout: '00:05:00'
        continue_on_timeout: false
      - service: telegram_bot.edit_message
        data:
          chat_id: !secret telegram_chat_id_bruce_and_sarah
          message_id: "{{ states('input_text.alarm_disarming_message_id') }}"            
          title: "{{ states('input_text.last_person_to_arrive') }} arriving."
          message: "Alarm disarming......"
      - service: alarm_control_panel.alarm_disarm 
        data:
          entity_id: alarm_control_panel.full_set
          code: !secret alarm_code
      - wait_template: "{{ is_state('alarm_control_panel.full_set','disarmed') }}"
        timeout: 00:00:10
      - service: telegram_bot.edit_message
        data:
          chat_id: !secret telegram_chat_id_bruce_and_sarah
          message_id: "{{ states('input_text.alarm_disarming_message_id') }}"  
          title: "Alarm is now {{states('alarm_control_panel.full_set').replace('_',' ')}}"
          message: "{{ states('input_text.last_person_to_arrive') }} has arrived."    
