# Don't think this works ??????????

automation:
  - id: texecom_alarm_warn_doors
    alias: Intruder Alarm warn about open doors on arming
    description: Intruder Alarm warn doors on arming
    trigger:
      - platform: state
        entity_id: alarm_control_panel.texecom
        from: 'disarmed'
        to: 'pending'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: 
            - binary_sensor.lounge_door
            - fan.bedroom_fan
            - fan.conservatory_fan
            - input_boolean.watching_skytv 
            - binary_sensor.conservatory_door 
            - binary_sensor.front_door
            - binary_sensor.back_gate_door
            - binary_sensor.back_door
            - binary_sensor.under_stairs_door
            - binary_sensor.kates_bedroom_door
            - binary_sensor.sophies_bedroom_door
            - binary_sensor.master_bedroom_door
            - binary_sensor.bar_door
            - binary_sensor.lounge_door
          state: 'on'
        - condition: state
          entity_id: 
            - media_player.kitchen_sonos
            - media_player.sophies_sonos
            - media_player.kates_sonos
            - media_player.master_bed_sonos
            - media_player.bar_sonos
            - media_player.lounge_sonos
          state: playing
        # Doors closed that should be open
        - condition: state
          entity_id: 
            - binary_sensor.main_bathroom_door
            - binary_sensor.downstairs_toilet_door
            - binary_sensor.drum_room_door
          state: 'off'          
    action:
      - service: telegram_bot.send_message
        data:
          target: !secret telegram_chat_id_bruce_and_sarah
          title: Alarm is setting
          message: >
            {{ 'Bedroom Fan is on' if is_state('fan.bedroom_fan','on') }}
            {{ 'Conservatory Fan is on' if is_state('fan.conservatory_fan','on') }}
            {% if is_state('input_boolean.watching_skytv','on') %}TV on in lounge
            {% endif %}
            {% if is_state('media_player.kitchen_sonos','playing') %}SONOS playing in the kitchen
            {% endif %}
            {% if is_state('media_player.sophies_sonos','playing') %}SONOS playing in Sophie bedroom
            {% endif %}
            {% if is_state('media_player.kates_sonos','playing') %}SONOS playing in Kate bedroom
            {% endif %}
            {% if is_state('media_player.lounge_sonos','playing') %}SONOS playing in the Lounge
            {% endif %}
            {% if is_state('media_player.bar_sonos','playing') %}SONOS playing in the Bar
            {% endif %}
            {% if is_state('binary_sensor.conservatory_door','on') %}conservatory door is open
            {% endif %}
            {% if is_state('binary_sensor.front_door','on') %}front door is open
            {% endif %}
            {% if is_state('binary_sensor.back_gate_door','on') %}back gate is open
            {% endif %}
            {% if is_state('binary_sensor.back_door','on') %}back door is open
            {% endif %}
            {% if is_state('binary_sensor.under_stairs_door','on') %}under stairs door is open
            {% endif %}
            {% if is_state('binary_sensor.master_bedroom_door','on') %}master bedroom door is open
            {% endif %}
            {% if is_state('binary_sensor.lounge_door','on') %}lounge door is open
            {% endif %}
            {% if is_state('binary_sensor.bar_door','on') %}bar door is open
            {% endif %}
            {% if is_state('binary_sensor.sophies_bedroom_door','on') %}Sophie's door is open
            {% endif %}
            {% if is_state('binary_sensor.kates_bedroom_door','on') %}Kate's door is open
            {% endif %}
            {% if is_state('binary_sensor.downstairs_toilet_door','off') %}Downstairs Loo door is closed
            {% endif %}
            {% if is_state('binary_sensor.main_bathroom_door','off') %}Bathroom door is closed
            {% endif %}
