automation:
  - id: hottub_turn_on_off_scheduled_when_time_changed
    alias: HotTub Turn on or off scheduled when time changed
    trigger:
      - platform: state
        entity_id: input_datetime.hottub_ready_by
      - platform: time
        at: input_datetime.hottub_ready_by
    action:
      - choose:
          - conditions: "{{ trigger.entity_id == 'input_datetime.hottub_ready_by' }}"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.hottub_scheduled
        default:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.hottub_scheduled