automation:
  - id: hottub_change_target
    alias: 'HotTub Change Target'
    mode: restart
    
    description: >
      Change target when input number updated
      
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded    
      - platform: state
        entity_id: 
          - input_number.hottub_water_target
          - sensor.hottub_target_temp

        
    action:
      - choose:
          - conditions: "{{ trigger.entity_id == 'input_number.hottub_water_target' }}"
            sequence:
              # Delay in case you change it again quickly
              - delay: 5
              - service: climate.set_temperature
                target: 
                  entity_id: climate.spa_climate
                data:
                  temperature: "{{ states('input_number.hottub_water_target') | int}}"
          - conditions: "{{ states('sensor.hottub_target_temp') | float > 27.0 }}"                  
            sequence:
              - service: input_number.set_value
                target:
                  entity_id: input_number.hottub_water_target
                data:
                  value: "{{ states('sensor.hottub_target_temp') | int }}"
