sensor:
  - platform: template
    sensors:
      hottub_schedule_target_temp:
        friendly_name: "HotTub Schedule Target Temp"
        device_class: temperature
        unit_of_measurement: '°C'
        value_template: "{{ [(states('input_number.hottub_standard_temp') | float - (([0,(as_timestamp(states('input_datetime.hottub_ready_by')) - as_timestamp(now())) / 3600] | max) * states('input_number.hottub_temp_rise_per_hour') | float)) | round(1,'half'),28] | max }}"
#          {% set HoursLeft =  [0,(as_timestamp(states('input_datetime.hottub_ready_by')) - as_timestamp(now())) / 3600] | max %}
#          {% set TempRisePerHour = states('input_number.hottub_temp_rise_per_hour') | float %}
#          {% set HotTubTarget = states('input_number.hottub_standard_temp') | float %}
#          {{ [(HotTubTarget - (HoursLeft * TempRisePerHour)) | round(1,'half'),28] | max }}

          
