sensor:
  - platform: template
    sensors:
      hottub_summary:
#        availability_template: "{{ not is_state('binary_sensor.spa_circ_pump','unavailable') }}"
        friendly_name: "HotTub Status"
        value_template: "{% if is_state('binary_sensor.spa_circ_pump','unavailable') %}offline{% elif is_state('binary_sensor.hot_tub_door','on') %}in use{% elif is_state('binary_sensor.spa_filter1','on') %}filtering{% elif state_attr('climate.spa_climate','hvac_action') == 'heating' %}heating{% elif is_state('binary_sensor.spa_circ_pump','on') %}circulating{% elif is_state('input_boolean.hottub_scheduled','on') %}scheduled{% else %}off{% endif %}"
        icon_template:  "{% if is_state('binary_sensor.spa_circ_pump','unavailable') %}mdi:access-point-off{% elif is_state('binary_sensor.hot_tub_door','on') %}mdi:pool{% elif is_state('binary_sensor.spa_filter1','on') %}mdi:air-filter{% elif state_attr('climate.spa_climate','hvac_action') == 'heating' %}mdi:fire{% elif is_state('binary_sensor.spa_circ_pump','on') %}mdi:water-pump{% elif is_state('input_boolean.hottub_scheduled','on') %}mdi:clock{% else %}mdi:power-standby{% endif %}"


