sensor:
  - platform: template
    sensors:
      hottub_price:
        availability_template: "{{ states('binary_sensor.hottub_online') }}"
        friendly_name: "HotTub Price"
        value_template: "{% if is_state('sensor.hottub_summary','heating') %}{{ states('sensor.octopus_agile_current_rate') | float * 2 }}{% else %}0{% endif %}"
