automation:
  - id: hottub_change_target
    alias: 'HotTub Change Target'
    mode: restart
    
    description: >
      Change target when input number updated
      
    trigger:
      - platform: state
        entity_id: 
          - input_number.hottub_water_target
        
    action:
      - delay: 5    
      - service: climate.set_temperature
        target: 
          entity_id: climate.spa_climate
        data:
          temperature: "{{ states('input_number.hottub_water_target') | int}}"

