sensor:
  - platform: history_stats
    name: HotTub Heating This Week
    entity_id: sensor.hottub_hvac_action
    state: "heating"
    type: time
    end: "{{ now().replace(hour=0, minute=0, second=0) }}"
    duration:
      days: 7