automation:
  # Set Girls Radiators based on calendar
  - id: set_guests_radiators
    alias: Set guests radiators
    description: set Guests rads from calendar
    trigger:
      - platform: time
        at: 
          - '06:00:00'
          - '13:00:00'
    action:
      - choose:
          - conditions: "{{ is_state('calendar.guest_yarbury','on') }}"
            sequence:
              - service: climate.set_hvac_mode
                data: 
                  entity_id: climate.guest_bedroom_rad
                  hvac_mode: 'auto'
          - conditions: 
              - condition: time
                after: '12:00:00'
            sequence:
              - service: climate.set_hvac_mode
                data: 
                  entity_id: climate.guest_bedroom_rad
                  hvac_mode: 'off'    