automation:
  - id: set_sophies_radiators
    alias: 'Set sophies radiators'

    description: >
      set Sophies rads from calendar
      
    trigger:
      - platform: time
        at: 
          - '06:00:00'
          - '13:00:00'
          
    action:
      - choose:
          - conditions: "{{ is_state('calendar.sophie_yarbury','on') }}"
            sequence:
              - service: climate.set_hvac_mode
                target: 
                  entity_id: climate.sophies_bedroom_rad
                data:
                  hvac_mode: 'auto'
          - conditions: 
              - condition: time
                after: '12:00:00'
            sequence:
              - service: climate.set_hvac_mode
                target: 
                  entity_id: climate.sophies_bedroom_rad
                data:
                  hvac_mode: 'off'                  
                  
                  