automation:
  - id: turn_on_k_heating
    alias: Turn on Kate heating
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: TURN_ON_K_HEATING
    action:      
      - service: climate.set_hvac_mode
        data: 
          entity_id: 
            - climate.kates_bedroom_rad
            - climate.kates_bathroom_rad
          hvac_mode: auto