binary_sensor:
  - platform: template
    sensors:
      lounge_rad_low_battery:
        friendly_name: 'Lounge Rad - Low Battery'
        value_template: "{{ (states('sensor.lounge_rad_battery_level') | float) < 20.0 }}"
      lounge_bay_rad_low_battery:
        friendly_name: 'Lounge Bay Rad - Low Battery'
        value_template: "{{ (states('sensor.lounge_bay_rad_battery_level') | float) < 20.0 }}"
      hall_rad_low_battery:
        friendly_name: 'Hall Rad - Low Battery'
        value_template: "{{ (states('sensor.hall_rad_battery_level') | float) < 20.0 }}"
      conservatory_rad_low_battery:
        friendly_name: 'Conservatory Rad - Low Battery'
        value_template: "{{ (states('sensor.conservatory_rad_battery_level') | float) < 20.0 }}"     
      kitchen_rad_low_battery:
        friendly_name: 'Kitchen Rad - Low Battery'
        value_template: "{{ (states('sensor.kitchen_rad_battery_level') | float) < 20.0 }}"
      kitchen_tall_rad_low_battery:
        friendly_name: 'Kitchen Tall Rad - Low Battery'
        value_template: "{{ (states('sensor.kitchen_tall_rad_battery_level') | float) < 20.0 }}"
      downstairs_loo_rad_low_battery:
        friendly_name: 'Downstairs Loo Rad - Low Battery'
        value_template: "{{ (states('sensor.downstairs_loo_rad_battery_level') | float) < 20.0 }}"    
      bar_rad_low_battery:
        friendly_name: 'Bar Rad - Low Battery'
        value_template: "{{ (states('sensor.bar_rad_battery_level') | float) < 20.0 }}"
      drum_room_rad_low_battery:
        friendly_name: 'Drum Room Rad - Low Battery'
        value_template: "{{ (states('sensor.drum_room_rad_battery_level') | float) < 20.0 }}"
      sophies_bedroom_rad_low_battery:
        friendly_name: "Sophie's Bedroom Rad - Low Battery"
        value_template: "{{ (states('sensor.sophies_bedroom_rad_battery_level') | float) < 20.0 }}"           
      kates_bedroom_rad_low_battery:
        friendly_name: "Kate's Bedroom Rad - Low Battery"
        value_template: "{{ (states('sensor.kates_bedroom_rad_battery_level') | float) < 20.0 }}"             
      kates_bathroom_rad_low_battery:
        friendly_name: "Kate's Bathroom Rad - Low Battery"
        value_template: "{{ (states('sensor.kates_bathroom_rad_battery_level') | float) < 20.0 }}"             
      guest_bedroom_rad_low_battery:
        friendly_name: 'Guest Bedroom Rad - Low Battery'
        value_template: "{{ (states('sensor.guest_bedroom_rad_battery_level') | float) < 20.0 }}"              
      master_bedroom_rad_low_battery:
        friendly_name: 'Master Bedroom Rad - Low Battery'
        value_template: "{{ (states('sensor.master_bedroom_rad_battery_level') | float) < 20.0 }}"                
      landing_1_rad_low_battery:
        friendly_name: 'Landing 1 Bedroom Rad - Low Battery'
        value_template: "{{ (states('sensor.landing_1_rad_battery_level') | float) < 20.0 }}"              
      landing_2_rad_low_battery:
        friendly_name: 'Landing 2 Bedroom Rad - Low Battery'
        value_template: "{{ (states('sensor.landing_2_rad_battery_level') | float) < 20.0 }}"    

