automation:
  - id: solcast_update_forecast
    alias: 'Solcast Update Forecast'
    
    description: >
      Update forecast each hour
      
    trigger:
      platform: time
      at:
        - '00:01:00'          
        - '05:00:00'           
        - '06:00:00'      
        - '07:00:00'       
        - '08:00:00'               
        - '09:00:00'                       
        - '10:00:00'               
        - '11:00:00'            
        - '12:00:00'
        - '13:00:00'                    
        - '14:00:00'        
        - '15:00:00'                
        - '16:00:00'
        - '17:00:00'        
        - '18:00:00'                                
        - '19:00:00'                                        
        - '20:00:00'                                                                                       
        - '21:50:00'   
        
    action:
      - service: solcast.update_forecast
#      - service: solcastx.update_forecast      
