automation:
  - id: solcast_update_forecast
    alias: 'Solcast Update Forecast'
    
    description: >
      Update forecast each half hour
      
    trigger:
#      - platform: time
#        at: '21:50:00'   
      - platform: time_pattern
        minutes: "/30"
        
#    condition:
#      - condition: time
#        after: '05:00:00'
#        before: '22:00:00'
        
    action:
      - service: solcast.update_forecast
#      - service: solcastx.update_forecast      
