automation:
  - id: solcast_update_tpday_forecast
    alias: "Solcast Update Today Forecast"
    trigger:
      platform: state
      entity_id: 
        - sensor.solcast_forecast
#        - sensor.solcast_forecast_a        
#        - sensor.solcast_forecast_b        
    action:
      - service: input_number.set_value
        data:
          entity_id: input_number.solcast_latest_today_forecast
          value: "{{ (states('sensor.solar_production_daily') | float + states('sensor.solcast_forecast') | float ) | round(1) }}"
#          value: "{{ (states('sensor.solar_production_daily') | float + states('sensor.solcast_forecast_a') | float + states('sensor.solcast_forecast_b') | float ) | round(1) }}"          
