automation:
  - id: solcast_update_forecast
    alias: 'Solcast Update Forecast'
    
    description: >
      Update forecast each half hour
      
    trigger:
      - platform: time_pattern
        minutes: "/30"
                
    action:
      - service: solcast.update_forecast
#      - service: solcastx.update_forecast      
