sensor:
  - platform: template
    sensors:
        solcast_forecast_the_day_after_tomorrow:
            friendly_name: "SolCast the Day After Tomorrow"
            unit_of_measurement: 'kWh'
            device_class: power            
            value_template: "{{ state_attr('sensor.solcast_forecast', 'the day after tomorrow')  }}"    
            