binary_sensor:
  - platform: template
    sensors:
      litter_trays_dirty:
        unique_id: litter_trays_dirty
        friendly_name: 'Litter Trays Dirty'
        value_template: >
          {% set sensors = [states.binary_sensor.littertray_utility_dirty,
                            states.binary_sensor.littertray_shower_dirty,
                            states.binary_sensor.littertray_downstairs_dirty,
                            states.binary_sensor.littertray_drum_dirty] %}
          {{ sensors | selectattr('state','eq','on') | list | count > 0 }}