sensor:
  - platform: template
    sensors:
      voltaware_active_exp:
        unique_id: voltaware_active_exp
        friendly_name_template: 'Produced Energy (P)'
        value_template: "{{ state_attr('sensor.voltaware','active_exp') / 1000 }}"
        unit_of_measurement: 'Wh'
        device_class: energy
