sensor:
  - platform: template
    sensors:
      voltaware_i:
        friendly_name_template: 'Current'
        value_template: "{{ state_attr('sensor.voltaware','I') / 1000 }}"
        unit_of_measurement: 'A'
        device_class: current                    
