sensor:
  - platform: template
    sensors:
      voltaware_reactive_exp:
        unique_id: voltaware_reactive_exp
        friendly_name_template: 'Produced Energy (Q)'
        value_template: "{{ state_attr('sensor.voltaware','reactive_exp') / 1000 }}"
        unit_of_measurement: 'varh'
