sensor:
  - platform: template
    sensors:
      voltaware_v:
        friendly_name_template: 'Voltage'
        value_template: "{{ state_attr('sensor.voltaware','V') / 1000 }}"
        unit_of_measurement: 'V'
        device_class: voltage                    
